name: expen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_material_pickers: ^3.7.0
  provider: ^6.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700